[
  {
    "Id": "943034",
    "ThreadId": "403548",
    "Html": "\r\n<p>I accidentally tried to overload a method as follows -&nbsp;note the incorrect use of uppercase &quot;String&quot;.</p>\r\n<p>public static getKeyCode(value: <strong>String</strong>): number;</p>\r\n<p>Everything was building fine until I tried to <span style=\"text-decoration:underline\">\r\ncall</span>&nbsp;the method, e.g. StringUtility.getKeyCode(&quot;a&quot;); Suddenly the compiler would fail with exit code 1, but with no useful error message at all.&nbsp;After quite awhile, I finally realized my mistake:</p>\r\n<p>public static getKeyCode(value: <strong>string</strong>): number;</p>\r\n<p>Now everything compiles and runs fine, but I found that to be a tricky bug to track down, especially since String is a valid type. I would've at least expected an error message complaining about me using the wrong type.</p>\r\n",
    "PostedDate": "2012-11-16T13:56:18.997-08:00",
    "UserRole": null,
    "MarkedAsAnswerDate": null
  },
  {
    "Id": "944624",
    "ThreadId": "403548",
    "Html": "\r\n<p>Failing without an error message is definitely a bug.&nbsp; Copying this over to the issue tracker.</p>\r\n",
    "PostedDate": "2012-11-20T08:01:52.843-08:00",
    "UserRole": null,
    "MarkedAsAnswerDate": null
  },
  {
    "Id": "944626",
    "ThreadId": "403548",
    "Html": "This discussion has been copied to a work item. Click <a href=\"http://typescript.codeplex.com/workitem/458\">here</a> to go to the work item and continue the discussion.",
    "PostedDate": "2012-11-20T08:01:58.017-08:00",
    "UserRole": null,
    "MarkedAsAnswerDate": null
  }
]