{
  "WorkItem": {
    "AffectedComponent": {
      "Name": "",
      "DisplayName": ""
    },
    "ClosedComment": "Fixed in develop branch",
    "ClosedDate": "2013-06-13T11:15:28.447-07:00",
    "CommentCount": 1,
    "Custom": null,
    "Description": "Given these two modules, TypeScript is unable to compile:\n\nModule: A.ts\n===========\nimport Module_B = module(\"B\");\n\nexport interface A_Wrapper {\n    wrap: A;\n}\n\nexport class A { };\n\nvar b = new Module_B.B();\n\nModule: B.ts\n===========\nimport Module_A = module(\"A\");\n\nexport class B {\n    // Comment Comment\n    instanceA: Module_A.A;\n\n    foo() {\n        var x = <Module_A.A_Wrapper>({}); // this line triggers the error\n    }\n}\n\nModule B uses Module A only for type-checking. The error appears in the Comment \"// Comment Comment\" line and says: \"The name 'A' does not exist in the current scope\". The position of the error also depends on where the interface A_Wrapper is positioned within A.ts (before or after the class) and on how long the commented line was - that's why it said \"Comment\" twice. So, the error just randomly appears in the code.",
    "LastUpdatedDate": "2014-01-10T10:34:33.287-08:00",
    "PlannedForRelease": "",
    "ReleaseVisibleToPublic": false,
    "Priority": {
      "Name": "Low",
      "Severity": 50,
      "Id": 1
    },
    "ProjectName": "typescript",
    "ReportedDate": "2012-11-07T11:35:39.333-08:00",
    "Status": {
      "Name": "Closed",
      "Id": 4
    },
    "ReasonClosed": {
      "Name": "Fixed"
    },
    "Summary": "Cyclic import triggers a \"does not exist in current scope\" in specific situation",
    "Type": {
      "Name": "Issue",
      "Id": 3
    },
    "VoteCount": 2,
    "Id": 386
  },
  "FileAttachments": [],
  "Comments": [
    {
      "Message": "Thanks for reporting the issue - marking it Active (to be fixed)",
      "PostedDate": "2012-11-13T16:22:15.357-08:00",
      "Id": 82434
    }
  ]
}