{
  "WorkItem": {
    "AffectedComponent": {
      "Name": "",
      "DisplayName": ""
    },
    "ClosedComment": "Fixed in develop branch",
    "ClosedDate": "2013-06-13T11:21:19.337-07:00",
    "CommentCount": 1,
    "Custom": null,
    "Description": "Issue workitem #35 seems to be closed, but I still see it in the 0.8.3 compiler.\r\nhttp://typescript.codeplex.com/workitem/35\r\n\r\nThe bug appears if running the compiler from node, but you don't see the error if running from tsc.exe.\r\n\r\nIt's not a huge issue because of the workaround, but the __proto__ field is common in existing javaScript code and it's not obvious what is causing it.",
    "LastUpdatedDate": "2014-01-10T10:34:33.287-08:00",
    "PlannedForRelease": "",
    "ReleaseVisibleToPublic": false,
    "Priority": {
      "Name": "Unassigned",
      "Severity": 0,
      "Id": 0
    },
    "ProjectName": "typescript",
    "ReportedDate": "2013-02-28T05:45:10.677-08:00",
    "Status": {
      "Name": "Closed",
      "Id": 4
    },
    "ReasonClosed": {
      "Name": "Fixed"
    },
    "Summary": "__proto__ Internal Compiler Error bug still there in 8.3",
    "Type": {
      "Name": "Issue",
      "Id": 3
    },
    "VoteCount": 1,
    "Id": 770
  },
  "FileAttachments": [],
  "Comments": [
    {
      "Message": "We've re-opened the bug internally, and see how it goes :)",
      "PostedDate": "2013-03-01T18:02:54.997-08:00",
      "Id": 92033
    }
  ]
}